language: en
pipeline: 
  - name: "WhitespaceTokenizer"
  - name: "RegexFeaturizer"
  - name: "CRFEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: "CountVectorsFeaturizer"
  - name: "DIETClassifier"
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    epochs: 80
